version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-network

  app:
    build: .
    volumes:
      - .:/var/www/html
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - todo-network

volumes:
  db_data:

networks:
  todo-network:
    driver: bridge